name: Generate Sitemap

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          echo '  <url><loc>https://0weyim1.github.io/0-Or-1-Journal-of-Cards/index.html</loc><priority>1.0</priority></url>' >> sitemap.xml
          find . -type f -name "*.html" \
            | grep -v -e '/node_modules/' -e '/\.git/' -e '/\.github/' -e '404.html' \
            | sort | while read -r file; do
            url="https://0weyim1.github.io/0-Or-1-Journal-of-Cards/index.html${file#./}"
            echo "  <url><loc>${url}</loc><priority>0.8</priority></url>" >> sitemap.xml
          done
          echo '</urlset>' >> sitemap.xml
          echo "Generated sitemap:"
          cat sitemap.xml

      - name: Commit and Push Sitemap
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sitemap.xml
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-generated sitemap update [skip ci]"
            git push origin main
          fi
