name: Generate Sitemap

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to get full git history for proper diffing

      - name: Generate Sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          echo '    <url><loc>https://0weyim1.github.io/0-Or-1-Journal-of-Cards/index.html</loc><priority>1.0</priority></url>' >> sitemap.xml
          
          # Find all HTML files (excluding node_modules and other common directories)
          find . -type f -name "*.html" \
            | grep -v -e '/node_modules/' -e '/\.git/' -e '/\.github/' \
            | sort | while read -r file; do
            url="https://0weyim1.github.io/0-Or-1-Journal-of-Cards/index.html${file#./}"
            echo "    <url><loc>${url}</loc><priority>0.8</priority></url>" >> sitemap.xml
          done
          
          echo '</urlset>' >> sitemap.xml

      - name: Commit and Push Sitemap
        run: |
          # Only proceed if sitemap.xml actually changed
          if git diff --quiet --exit-code sitemap.xml; then
            echo "No changes to sitemap.xml"
            exit 0
          fi
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Auto-generated sitemap update [skip ci]"
          git push
